version: '3.9'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-17.1}
    container_name: postgres-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-unitdatatbase}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
    networks:
      - postgres_network
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

networks:
  postgres_network:
    driver: bridge
